name: el_tooltip2
description: ElTooltip, a smart positioned tooltip. Use it to display a widget inside a tooltip that you can personalize. With a few changes, Thanks to marcelogil
version: 1.1.1
repository: https://github.com/Yavmarto/el_tooltip

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
